import { CategoryInfo } from './types';

export const CATEGORIES: CategoryInfo[] = [
  {
    slug: 'all',
    name: 'All',
    icon: '🔥',
    description: 'Every project on the Outbid leaderboard competing for glory',
  },
  {
    slug: 'seo-ai-visibility',
    name: 'SEO & AI Visibility',
    icon: '🔍',
    description: 'Search engine optimization, LLM indexing, and AI visibility tools',
  },
  {
    slug: 'ai-agents-infrastructure',
    name: 'AI Agents & Infrastructure',
    icon: '🤖',
    description: 'Autonomous agents, LLM orchestration, model hosting, and AI dev platforms',
  },
  {
    slug: 'ai-media-generation',
    name: 'AI Media Generation',
    icon: '✨',
    description: 'Image generation, video creation, voice synthesis, and creative AI tools',
  },
  {
    slug: 'marketing-advertising',
    name: 'Marketing & Advertising',
    icon: '📢',
    description: 'Paid ads, affiliate software, social growth, and email automation',
  },
  {
    slug: 'developer-tools',
    name: 'Developer Tools',
    icon: '</>',
    description: 'Frameworks, SDKs, APIs, databases, UI component kits, and code editors',
  },
  {
    slug: 'productivity-personal-tools',
    name: 'Productivity & Personal Tools',
    icon: '⏱️',
    description: 'Project management, task planners, note-taking, and workflow utilities',
  },
  {
    slug: 'people-profiles',
    name: 'People & Profiles',
    icon: '👤',
    description: 'Founders, creators, developers, designers, and personal brands',
  },
  {
    slug: 'design-creative',
    name: 'Design & Creative',
    icon: '🎨',
    description: 'UI/UX kits, vector graphics, design systems, and creative tools',
  },
  {
    slug: 'social-media-creator-tools',
    name: 'Social Media & Creator Tools',
    icon: '📱',
    description: 'X schedulers, TikTok utilities, creator tools, and cross-posters',
  },
  {
    slug: 'writing-content',
    name: 'Writing & Content',
    icon: '✍️',
    description: 'Copywriting assistants, blogs, newsletters, and ghostwriting tools',
  },
  {
    slug: 'sales-lead-generation',
    name: 'Sales & Lead Generation',
    icon: '🎯',
    description: 'Cold email tools, lead finders, CRM integrations, and outreach platforms',
  },
  {
    slug: 'business-finance-legal',
    name: 'Business, Finance & Legal',
    icon: '💼',
    description: 'Accounting software, bookkeeping, LLC formation, and business tools',
  },
  {
    slug: 'games-entertainment',
    name: 'Games & Entertainment',
    icon: '🎮',
    description: 'Web games, interactive bots, streaming tools, and media platforms',
  },
  {
    slug: 'education-learning',
    name: 'Education & Learning',
    icon: '🎓',
    description: 'Research assistants, reading tutors, courses, and educational apps',
  },
  {
    slug: 'health-fitness-wellness',
    name: 'Health, Fitness & Wellness',
    icon: '❤️',
    description: 'Calorie counters, fitness planners, wellness trackers, and peptide DBs',
  },
  {
    slug: 'ecommerce-retail',
    name: 'Ecommerce & Retail',
    icon: '🛍️',
    description: 'Online stores, Shopify apps, dropshipping tools, and commerce APIs',
  },
  {
    slug: 'directories-launch-discovery',
    name: 'Directories, Launch & Discovery',
    icon: '🚀',
    description: 'Product directories, curated lists, launchpads, and discovery engines',
  },
  {
    slug: 'hiring-jobs-careers',
    name: 'Hiring, Jobs & Careers',
    icon: '🤝',
    description: 'Talent marketplaces, job boards, resume analyzers, and recruiting tools',
  },
  {
    slug: 'audio-voice-podcasting',
    name: 'Audio, Voice & Podcasting',
    icon: '🎙️',
    description: 'Voice cloning, podcast hosting, text-to-speech, and audio editors',
  },
  {
    slug: 'crypto-web3-investing',
    name: 'Crypto, Web3 & Investing',
    icon: '🪙',
    description: 'DeFi protocols, memecoins, crypto wallets, and trading platforms',
  },
  {
    slug: 'agencies-studios-services',
    name: 'Agencies, Studios & Services',
    icon: '🏢',
    description: 'Product design studios, growth agencies, dev shops, and SEO agencies',
  },
  {
    slug: 'security-privacy-compliance',
    name: 'Security, Privacy & Compliance',
    icon: '🛡️',
    description: 'SOC 2 automation, pentesting, HIPAA compliance, and privacy tools',
  },
  {
    slug: 'travel-local-lifestyle',
    name: 'Travel, Local & Lifestyle',
    icon: '✈️',
    description: 'Travel planners, booking tools, local discovery, and nomad guides',
  },
  {
    slug: 'media-news',
    name: 'Media & News',
    icon: '📰',
    description: 'Tech newsletters, media publications, industry aggregators, and podcasts',
  },
  {
    slug: 'domains-web-assets',
    name: 'Domains & Web Assets',
    icon: '🌐',
    description: 'Domain marketplaces, premium names, brandable assets, and brokerages',
  },
  {
    slug: 'leaderboards-attention',
    name: 'Leaderboards & Attention Markets',
    icon: '👑',
    description: 'Pay-to-rank boards, attention games, bidding markets, and hall of fames',
  },
  {
    slug: 'real-estate-property',
    name: 'Real Estate & Property',
    icon: '🏠',
    description: 'Property search engines, real estate CRM, rental tools, and analytics',
  },
  {
    slug: 'other',
    name: 'Other',
    icon: '⚡',
    description: 'Everything else competing on the global leaderboard',
  },
];
