import { CategoryInfo } from './types';

export const CATEGORIES: CategoryInfo[] = [
  {
    slug: 'all',
    name: 'All',
    icon: '⊞',
    description: 'Every project on the Outbid leaderboard competing for glory',
  },
  {
    slug: 'agencies-studios-services',
    name: 'Agencies',
    icon: '🏢',
    description: 'Product design studios, growth agencies, dev shops, and marketing agencies',
  },
  {
    slug: 'ai-agents-infrastructure',
    name: 'AI Agents',
    icon: '🤖',
    description: 'Autonomous agents, LLM orchestration, model hosting, and AI dev platforms',
  },
  {
    slug: 'ai-media-generation',
    name: 'AI Media',
    icon: '✨',
    description: 'Image generation, video creation, voice synthesis, and creative AI tools',
  },
  {
    slug: 'audio-voice-podcasting',
    name: 'Audio',
    icon: '🎙',
    description: 'Voice cloning, podcast hosting, text-to-speech, and audio tools',
  },
  {
    slug: 'business-finance-legal',
    name: 'Finance',
    icon: '⚖️',
    description: 'Accounting software, bookkeeping, investing tools, and legal tech',
  },
  {
    slug: 'crypto-web3-investing',
    name: 'Crypto',
    icon: '₿',
    description: 'DeFi protocols, memecoins, crypto wallets, and trading platforms',
  },
  {
    slug: 'design-creative',
    name: 'Design & Dev',
    icon: '🎨',
    description: 'UI/UX kits, vector graphics, design systems, and developer tools',
  },
  {
    slug: 'seo-ai-visibility',
    name: 'SEO & AI Visibility',
    icon: '🔍',
    description: 'Search engine optimization, LLM indexing, and AI visibility tools',
  },
  {
    slug: 'developer-tools',
    name: 'Developer Tools',
    icon: '</>',
    description: 'Frameworks, SDKs, APIs, databases, UI component kits, and code editors',
  },
  {
    slug: 'marketing-advertising',
    name: 'Marketing & Ads',
    icon: '📢',
    description: 'Paid ads, affiliate software, social growth, and email automation',
  },
  {
    slug: 'productivity-personal-tools',
    name: 'Productivity',
    icon: '⏱️',
    description: 'Project management, task planners, note-taking, and workflow utilities',
  },
  {
    slug: 'people-profiles',
    name: 'People & Profiles',
    icon: '👤',
    description: 'Founders, creators, developers, designers, and personal brands',
  },
  {
    slug: 'social-media-creator-tools',
    name: 'Social Media',
    icon: '📱',
    description: 'X schedulers, TikTok utilities, creator tools, and cross-posters',
  },
  {
    slug: 'writing-content',
    name: 'Writing & Content',
    icon: '✍️',
    description: 'Copywriting assistants, blogs, newsletters, and ghostwriting tools',
  },
  {
    slug: 'sales-lead-generation',
    name: 'Sales & Leads',
    icon: '🎯',
    description: 'Cold email tools, lead finders, CRM integrations, and outreach platforms',
  },
  {
    slug: 'games-entertainment',
    name: 'Games & Fun',
    icon: '🎮',
    description: 'Web games, interactive bots, streaming tools, and media platforms',
  },
  {
    slug: 'education-learning',
    name: 'Education',
    icon: '🎓',
    description: 'Research assistants, reading tutors, courses, and educational apps',
  },
  {
    slug: 'health-fitness-wellness',
    name: 'Health & Wellness',
    icon: '❤️',
    description: 'Calorie counters, fitness planners, wellness trackers, and longevity tools',
  },
  {
    slug: 'ecommerce-retail',
    name: 'Ecommerce',
    icon: '🛍️',
    description: 'Online stores, Shopify apps, dropshipping tools, and commerce APIs',
  },
  {
    slug: 'directories-launch-discovery',
    name: 'Directories & Launch',
    icon: '🚀',
    description: 'Product directories, curated lists, launchpads, and discovery engines',
  },
  {
    slug: 'hiring-jobs-careers',
    name: 'Hiring & Jobs',
    icon: '🤝',
    description: 'Talent marketplaces, job boards, resume analyzers, and recruiting tools',
  },
  {
    slug: 'security-privacy-compliance',
    name: 'Security & Privacy',
    icon: '🛡️',
    description: 'SOC 2 automation, pentesting, HIPAA compliance, and privacy tools',
  },
  {
    slug: 'travel-local-lifestyle',
    name: 'Travel & Lifestyle',
    icon: '✈️',
    description: 'Travel planners, booking tools, local discovery, and nomad guides',
  },
  {
    slug: 'other',
    name: 'Other',
    icon: '⚡',
    description: 'Everything else competing on the global leaderboard',
  },
];
